# Generated by Django 4.0 on 2024-07-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_post_likes_alter_post_content_alter_reply_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
