# Generated by Django 4.0 on 2024-07-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_hashtag_name_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='picture',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
