# Generated by Django 4.0 on 2024-07-24 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0007_reply_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('anthropic_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('google_gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mistral_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('perplexity_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
