# Generated by Django 4.0 on 2024-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='together_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
