# Generated by Django 5.0.2 on 2024-03-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
