# Generated by Django 5.0.3 on 2024-03-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_course_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
